### ISSUE TITLE
Basic example does not work

### ISSUE THREAD

**Issue by zerazerg** [brmcerqueira/deninject#1]
Hi!

I just tried to use this library and it gives me "random" errors...

So I tried the basic example ad it just fails.
> `deno run -A test.ts`
<pre>
Warning Implicitly using latest version (1.0.5) for https://deno.land/x/deninject/mod.ts
error: Uncaught Error: Bind not found for 'ClassB'.
            throw new BindError(identity, token);
                  ^
    at Injector.privateGet (https://deno.land/x/deninject@1.0.5/injector.ts:248:19)
    at Injector.get (https://deno.land/x/deninject@1.0.5/injector.ts:220:21)
    at file:///Users/obioscaa/Documents/_Curro/_T2C/_PoC/_deno_cucumber/test.ts:28:20
</pre>

Just to be clear, the copy-paste example tested is:
<pre>
import { Injector, Singleton, Transient } from "https://deno.land/x/deninject/mod.ts"; 

class ClassA {
    constructor() {
        console.log("buildA");
    }
}

class ClassB {
    constructor(a: ClassA) {
        console.log("buildB: ", a);
    }
}

class MyModule {
    @Singleton()
    public buildA(): ClassA {
        return new ClassA();
    }

    @Transient()
    public buildB(a: ClassA): ClassB {
        return new ClassB(a);
    }
}

const injector = new Injector(new MyModule());
const b = injector.get(ClassB);
</pre>

My `tsconfig.json` is...
<pre>
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
</pre>
... as specified in the docs here => https://deno.land/x/deninject@1.0.5#setup

**Comment by brmcerqueira** [comment]
Hi, @zerazerg.

I believe your test is ignoring your tsconfig.json. make sure if Deno is using thath tsconfig.json. if you want, you can put your code in github or similar, and share with me. maybe I can help you.

**Comment by zerazerg** [comment]
Hi!

I made a separate simple project using your "Hello world" + your feedback => https://github.com/zerazerg/deninject-issue-1-sandbox

Seems that _Deno_ compiler does not allow **all** the _Typescript_ options. In fact, when using their compiler file it tells that <pre>Unsupported compiler options in "file:///Users/obioscaa/Documents/_Curro/_T2C/_PoC/deninject-issue-1-sandbox/deno.jsonc".
  The following options were ignored:
    experimentalDecorators</pre>

* Do you know any workaround for this error?

It would be amazing to make it run in Deno also (which is _blazing fast_, by the way)
